/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChromeRouteImport } from './routes/_chrome'
import { Route as ChromeIndexRouteImport } from './routes/_chrome.index'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetSentRouteImport } from './routes/auth.reset-sent'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ChromeInternalRouteImport } from './routes/_chrome.internal'
import { Route as ChromeInstallRouteImport } from './routes/_chrome.install'
import { Route as ChromeAppRouteImport } from './routes/_chrome.app'
import { Route as ChromeInternalIndexRouteImport } from './routes/_chrome.internal.index'
import { Route as ChromeAppIndexRouteImport } from './routes/_chrome.app.index'
import { Route as ChromeInternalWebhooksRouteImport } from './routes/_chrome.internal.webhooks'
import { Route as ChromeInternalUsersRouteImport } from './routes/_chrome.internal.users'
import { Route as ChromeInternalInstallStateRouteImport } from './routes/_chrome.internal.install-state'
import { Route as ChromeInternalCacheRouteImport } from './routes/_chrome.internal.cache'
import { Route as ChromeInternalAiChatsRouteImport } from './routes/_chrome.internal.ai-chats'
import { Route as ChromeInternalActionAuditsRouteImport } from './routes/_chrome.internal.action-audits'
import { Route as ChromeAppWorkflowsRouteImport } from './routes/_chrome.app.workflows'
import { Route as ChromeAppSettingsRouteImport } from './routes/_chrome.app.settings'
import { Route as ChromeAppExplorerRouteImport } from './routes/_chrome.app.explorer'
import { Route as ChromeAppCopilotRouteImport } from './routes/_chrome.app.copilot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeRoute = ChromeRouteImport.update({
  id: '/_chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeIndexRoute = ChromeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChromeRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetSentRoute = AuthResetSentRouteImport.update({
  id: '/reset-sent',
  path: '/reset-sent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ChromeInternalRoute = ChromeInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => ChromeRoute,
} as any)
const ChromeInstallRoute = ChromeInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ChromeRoute,
} as any)
const ChromeAppRoute = ChromeAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ChromeRoute,
} as any)
const ChromeInternalIndexRoute = ChromeInternalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeAppIndexRoute = ChromeAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeInternalWebhooksRoute = ChromeInternalWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalUsersRoute = ChromeInternalUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalInstallStateRoute =
  ChromeInternalInstallStateRouteImport.update({
    id: '/install-state',
    path: '/install-state',
    getParentRoute: () => ChromeInternalRoute,
  } as any)
const ChromeInternalCacheRoute = ChromeInternalCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalAiChatsRoute = ChromeInternalAiChatsRouteImport.update({
  id: '/ai-chats',
  path: '/ai-chats',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalActionAuditsRoute =
  ChromeInternalActionAuditsRouteImport.update({
    id: '/action-audits',
    path: '/action-audits',
    getParentRoute: () => ChromeInternalRoute,
  } as any)
const ChromeAppWorkflowsRoute = ChromeAppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeAppSettingsRoute = ChromeAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeAppExplorerRoute = ChromeAppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeAppCopilotRoute = ChromeAppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => ChromeAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChromeIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app': typeof ChromeAppRouteWithChildren
  '/install': typeof ChromeInstallRoute
  '/internal': typeof ChromeInternalRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-sent': typeof AuthResetSentRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/copilot': typeof ChromeAppCopilotRoute
  '/app/explorer': typeof ChromeAppExplorerRoute
  '/app/settings': typeof ChromeAppSettingsRoute
  '/app/workflows': typeof ChromeAppWorkflowsRoute
  '/internal/action-audits': typeof ChromeInternalActionAuditsRoute
  '/internal/ai-chats': typeof ChromeInternalAiChatsRoute
  '/internal/cache': typeof ChromeInternalCacheRoute
  '/internal/install-state': typeof ChromeInternalInstallStateRoute
  '/internal/users': typeof ChromeInternalUsersRoute
  '/internal/webhooks': typeof ChromeInternalWebhooksRoute
  '/app/': typeof ChromeAppIndexRoute
  '/internal/': typeof ChromeInternalIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/install': typeof ChromeInstallRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-sent': typeof AuthResetSentRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof ChromeIndexRoute
  '/app/copilot': typeof ChromeAppCopilotRoute
  '/app/explorer': typeof ChromeAppExplorerRoute
  '/app/settings': typeof ChromeAppSettingsRoute
  '/app/workflows': typeof ChromeAppWorkflowsRoute
  '/internal/action-audits': typeof ChromeInternalActionAuditsRoute
  '/internal/ai-chats': typeof ChromeInternalAiChatsRoute
  '/internal/cache': typeof ChromeInternalCacheRoute
  '/internal/install-state': typeof ChromeInternalInstallStateRoute
  '/internal/users': typeof ChromeInternalUsersRoute
  '/internal/webhooks': typeof ChromeInternalWebhooksRoute
  '/app': typeof ChromeAppIndexRoute
  '/internal': typeof ChromeInternalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chrome': typeof ChromeRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_chrome/app': typeof ChromeAppRouteWithChildren
  '/_chrome/install': typeof ChromeInstallRoute
  '/_chrome/internal': typeof ChromeInternalRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-sent': typeof AuthResetSentRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_chrome/': typeof ChromeIndexRoute
  '/_chrome/app/copilot': typeof ChromeAppCopilotRoute
  '/_chrome/app/explorer': typeof ChromeAppExplorerRoute
  '/_chrome/app/settings': typeof ChromeAppSettingsRoute
  '/_chrome/app/workflows': typeof ChromeAppWorkflowsRoute
  '/_chrome/internal/action-audits': typeof ChromeInternalActionAuditsRoute
  '/_chrome/internal/ai-chats': typeof ChromeInternalAiChatsRoute
  '/_chrome/internal/cache': typeof ChromeInternalCacheRoute
  '/_chrome/internal/install-state': typeof ChromeInternalInstallStateRoute
  '/_chrome/internal/users': typeof ChromeInternalUsersRoute
  '/_chrome/internal/webhooks': typeof ChromeInternalWebhooksRoute
  '/_chrome/app/': typeof ChromeAppIndexRoute
  '/_chrome/internal/': typeof ChromeInternalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/install'
    | '/internal'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/reset-sent'
    | '/auth/sign-in'
    | '/app/copilot'
    | '/app/explorer'
    | '/app/settings'
    | '/app/workflows'
    | '/internal/action-audits'
    | '/internal/ai-chats'
    | '/internal/cache'
    | '/internal/install-state'
    | '/internal/users'
    | '/internal/webhooks'
    | '/app/'
    | '/internal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/install'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/reset-sent'
    | '/auth/sign-in'
    | '/'
    | '/app/copilot'
    | '/app/explorer'
    | '/app/settings'
    | '/app/workflows'
    | '/internal/action-audits'
    | '/internal/ai-chats'
    | '/internal/cache'
    | '/internal/install-state'
    | '/internal/users'
    | '/internal/webhooks'
    | '/app'
    | '/internal'
  id:
    | '__root__'
    | '/_chrome'
    | '/auth'
    | '/_chrome/app'
    | '/_chrome/install'
    | '/_chrome/internal'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/reset-sent'
    | '/auth/sign-in'
    | '/_chrome/'
    | '/_chrome/app/copilot'
    | '/_chrome/app/explorer'
    | '/_chrome/app/settings'
    | '/_chrome/app/workflows'
    | '/_chrome/internal/action-audits'
    | '/_chrome/internal/ai-chats'
    | '/_chrome/internal/cache'
    | '/_chrome/internal/install-state'
    | '/_chrome/internal/users'
    | '/_chrome/internal/webhooks'
    | '/_chrome/app/'
    | '/_chrome/internal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChromeRoute: typeof ChromeRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chrome': {
      id: '/_chrome'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chrome/': {
      id: '/_chrome/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChromeIndexRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-sent': {
      id: '/auth/reset-sent'
      path: '/reset-sent'
      fullPath: '/auth/reset-sent'
      preLoaderRoute: typeof AuthResetSentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_chrome/internal': {
      id: '/_chrome/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof ChromeInternalRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/_chrome/install': {
      id: '/_chrome/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof ChromeInstallRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/_chrome/app': {
      id: '/_chrome/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ChromeAppRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/_chrome/internal/': {
      id: '/_chrome/internal/'
      path: '/'
      fullPath: '/internal/'
      preLoaderRoute: typeof ChromeInternalIndexRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/app/': {
      id: '/_chrome/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ChromeAppIndexRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/internal/webhooks': {
      id: '/_chrome/internal/webhooks'
      path: '/webhooks'
      fullPath: '/internal/webhooks'
      preLoaderRoute: typeof ChromeInternalWebhooksRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/users': {
      id: '/_chrome/internal/users'
      path: '/users'
      fullPath: '/internal/users'
      preLoaderRoute: typeof ChromeInternalUsersRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/install-state': {
      id: '/_chrome/internal/install-state'
      path: '/install-state'
      fullPath: '/internal/install-state'
      preLoaderRoute: typeof ChromeInternalInstallStateRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/cache': {
      id: '/_chrome/internal/cache'
      path: '/cache'
      fullPath: '/internal/cache'
      preLoaderRoute: typeof ChromeInternalCacheRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/ai-chats': {
      id: '/_chrome/internal/ai-chats'
      path: '/ai-chats'
      fullPath: '/internal/ai-chats'
      preLoaderRoute: typeof ChromeInternalAiChatsRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/action-audits': {
      id: '/_chrome/internal/action-audits'
      path: '/action-audits'
      fullPath: '/internal/action-audits'
      preLoaderRoute: typeof ChromeInternalActionAuditsRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/app/workflows': {
      id: '/_chrome/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof ChromeAppWorkflowsRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/app/settings': {
      id: '/_chrome/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof ChromeAppSettingsRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/app/explorer': {
      id: '/_chrome/app/explorer'
      path: '/explorer'
      fullPath: '/app/explorer'
      preLoaderRoute: typeof ChromeAppExplorerRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/app/copilot': {
      id: '/_chrome/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof ChromeAppCopilotRouteImport
      parentRoute: typeof ChromeAppRoute
    }
  }
}

interface ChromeAppRouteChildren {
  ChromeAppCopilotRoute: typeof ChromeAppCopilotRoute
  ChromeAppExplorerRoute: typeof ChromeAppExplorerRoute
  ChromeAppSettingsRoute: typeof ChromeAppSettingsRoute
  ChromeAppWorkflowsRoute: typeof ChromeAppWorkflowsRoute
  ChromeAppIndexRoute: typeof ChromeAppIndexRoute
}

const ChromeAppRouteChildren: ChromeAppRouteChildren = {
  ChromeAppCopilotRoute: ChromeAppCopilotRoute,
  ChromeAppExplorerRoute: ChromeAppExplorerRoute,
  ChromeAppSettingsRoute: ChromeAppSettingsRoute,
  ChromeAppWorkflowsRoute: ChromeAppWorkflowsRoute,
  ChromeAppIndexRoute: ChromeAppIndexRoute,
}

const ChromeAppRouteWithChildren = ChromeAppRoute._addFileChildren(
  ChromeAppRouteChildren,
)

interface ChromeInternalRouteChildren {
  ChromeInternalActionAuditsRoute: typeof ChromeInternalActionAuditsRoute
  ChromeInternalAiChatsRoute: typeof ChromeInternalAiChatsRoute
  ChromeInternalCacheRoute: typeof ChromeInternalCacheRoute
  ChromeInternalInstallStateRoute: typeof ChromeInternalInstallStateRoute
  ChromeInternalUsersRoute: typeof ChromeInternalUsersRoute
  ChromeInternalWebhooksRoute: typeof ChromeInternalWebhooksRoute
  ChromeInternalIndexRoute: typeof ChromeInternalIndexRoute
}

const ChromeInternalRouteChildren: ChromeInternalRouteChildren = {
  ChromeInternalActionAuditsRoute: ChromeInternalActionAuditsRoute,
  ChromeInternalAiChatsRoute: ChromeInternalAiChatsRoute,
  ChromeInternalCacheRoute: ChromeInternalCacheRoute,
  ChromeInternalInstallStateRoute: ChromeInternalInstallStateRoute,
  ChromeInternalUsersRoute: ChromeInternalUsersRoute,
  ChromeInternalWebhooksRoute: ChromeInternalWebhooksRoute,
  ChromeInternalIndexRoute: ChromeInternalIndexRoute,
}

const ChromeInternalRouteWithChildren = ChromeInternalRoute._addFileChildren(
  ChromeInternalRouteChildren,
)

interface ChromeRouteChildren {
  ChromeAppRoute: typeof ChromeAppRouteWithChildren
  ChromeInstallRoute: typeof ChromeInstallRoute
  ChromeInternalRoute: typeof ChromeInternalRouteWithChildren
  ChromeIndexRoute: typeof ChromeIndexRoute
}

const ChromeRouteChildren: ChromeRouteChildren = {
  ChromeAppRoute: ChromeAppRouteWithChildren,
  ChromeInstallRoute: ChromeInstallRoute,
  ChromeInternalRoute: ChromeInternalRouteWithChildren,
  ChromeIndexRoute: ChromeIndexRoute,
}

const ChromeRouteWithChildren =
  ChromeRoute._addFileChildren(ChromeRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthResetSentRoute: typeof AuthResetSentRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResetSentRoute: AuthResetSentRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChromeRoute: ChromeRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
