/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChromeRouteImport } from './routes/_chrome'
import { Route as ChromeIndexRouteImport } from './routes/_chrome.index'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetSentRouteImport } from './routes/auth.reset-sent'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ChromeInternalRouteImport } from './routes/_chrome.internal'
import { Route as ChromeInstallRouteImport } from './routes/_chrome.install'
import { Route as ChromeAppRouteImport } from './routes/_chrome.app'
import { Route as ChromeInternalIndexRouteImport } from './routes/_chrome.internal.index'
import { Route as ChromeAppIndexRouteImport } from './routes/_chrome.app.index'
import { Route as ChromeInternalWorkflowsRouteImport } from './routes/_chrome.internal.workflows'
import { Route as ChromeInternalWebhooksRouteImport } from './routes/_chrome.internal.webhooks'
import { Route as ChromeInternalUsersRouteImport } from './routes/_chrome.internal.users'
import { Route as ChromeInternalShopsRouteImport } from './routes/_chrome.internal.shops'
import { Route as ChromeInternalCacheRouteImport } from './routes/_chrome.internal.cache'
import { Route as ChromeInternalAuditsRouteImport } from './routes/_chrome.internal.audits'
import { Route as ChromeInternalAiSessionsRouteImport } from './routes/_chrome.internal.ai-sessions'
import { Route as ChromeAppWorkflowsRouteImport } from './routes/_chrome.app.workflows'
import { Route as ChromeAppSettingsRouteImport } from './routes/_chrome.app.settings'
import { Route as ChromeAppExplorerRouteImport } from './routes/_chrome.app.explorer'
import { Route as ChromeAppCopilotRouteImport } from './routes/_chrome.app.copilot'
import { Route as ChromeInternalWorkflowsJobIdRouteImport } from './routes/_chrome.internal.workflows.$jobId'
import { Route as ChromeInternalWebhooksDeliveryIdRouteImport } from './routes/_chrome.internal.webhooks.$deliveryId'
import { Route as ChromeInternalUsersUserIdRouteImport } from './routes/_chrome.internal.users.$userId'
import { Route as ChromeInternalShopsShopIdRouteImport } from './routes/_chrome.internal.shops.$shopId'
import { Route as ChromeInternalCacheCacheStateIdRouteImport } from './routes/_chrome.internal.cache.$cacheStateId'
import { Route as ChromeInternalAuditsAuditIdRouteImport } from './routes/_chrome.internal.audits.$auditId'
import { Route as ChromeInternalAiSessionsSessionDocumentIdRouteImport } from './routes/_chrome.internal.ai-sessions.$sessionDocumentId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeRoute = ChromeRouteImport.update({
  id: '/_chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeIndexRoute = ChromeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChromeRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetSentRoute = AuthResetSentRouteImport.update({
  id: '/reset-sent',
  path: '/reset-sent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ChromeInternalRoute = ChromeInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => ChromeRoute,
} as any)
const ChromeInstallRoute = ChromeInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ChromeRoute,
} as any)
const ChromeAppRoute = ChromeAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ChromeRoute,
} as any)
const ChromeInternalIndexRoute = ChromeInternalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeAppIndexRoute = ChromeAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeInternalWorkflowsRoute = ChromeInternalWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalWebhooksRoute = ChromeInternalWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalUsersRoute = ChromeInternalUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalShopsRoute = ChromeInternalShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalCacheRoute = ChromeInternalCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalAuditsRoute = ChromeInternalAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => ChromeInternalRoute,
} as any)
const ChromeInternalAiSessionsRoute =
  ChromeInternalAiSessionsRouteImport.update({
    id: '/ai-sessions',
    path: '/ai-sessions',
    getParentRoute: () => ChromeInternalRoute,
  } as any)
const ChromeAppWorkflowsRoute = ChromeAppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeAppSettingsRoute = ChromeAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeAppExplorerRoute = ChromeAppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeAppCopilotRoute = ChromeAppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => ChromeAppRoute,
} as any)
const ChromeInternalWorkflowsJobIdRoute =
  ChromeInternalWorkflowsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => ChromeInternalWorkflowsRoute,
  } as any)
const ChromeInternalWebhooksDeliveryIdRoute =
  ChromeInternalWebhooksDeliveryIdRouteImport.update({
    id: '/$deliveryId',
    path: '/$deliveryId',
    getParentRoute: () => ChromeInternalWebhooksRoute,
  } as any)
const ChromeInternalUsersUserIdRoute =
  ChromeInternalUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ChromeInternalUsersRoute,
  } as any)
const ChromeInternalShopsShopIdRoute =
  ChromeInternalShopsShopIdRouteImport.update({
    id: '/$shopId',
    path: '/$shopId',
    getParentRoute: () => ChromeInternalShopsRoute,
  } as any)
const ChromeInternalCacheCacheStateIdRoute =
  ChromeInternalCacheCacheStateIdRouteImport.update({
    id: '/$cacheStateId',
    path: '/$cacheStateId',
    getParentRoute: () => ChromeInternalCacheRoute,
  } as any)
const ChromeInternalAuditsAuditIdRoute =
  ChromeInternalAuditsAuditIdRouteImport.update({
    id: '/$auditId',
    path: '/$auditId',
    getParentRoute: () => ChromeInternalAuditsRoute,
  } as any)
const ChromeInternalAiSessionsSessionDocumentIdRoute =
  ChromeInternalAiSessionsSessionDocumentIdRouteImport.update({
    id: '/$sessionDocumentId',
    path: '/$sessionDocumentId',
    getParentRoute: () => ChromeInternalAiSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChromeIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app': typeof ChromeAppRouteWithChildren
  '/install': typeof ChromeInstallRoute
  '/internal': typeof ChromeInternalRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-sent': typeof AuthResetSentRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/copilot': typeof ChromeAppCopilotRoute
  '/app/explorer': typeof ChromeAppExplorerRoute
  '/app/settings': typeof ChromeAppSettingsRoute
  '/app/workflows': typeof ChromeAppWorkflowsRoute
  '/internal/ai-sessions': typeof ChromeInternalAiSessionsRouteWithChildren
  '/internal/audits': typeof ChromeInternalAuditsRouteWithChildren
  '/internal/cache': typeof ChromeInternalCacheRouteWithChildren
  '/internal/shops': typeof ChromeInternalShopsRouteWithChildren
  '/internal/users': typeof ChromeInternalUsersRouteWithChildren
  '/internal/webhooks': typeof ChromeInternalWebhooksRouteWithChildren
  '/internal/workflows': typeof ChromeInternalWorkflowsRouteWithChildren
  '/app/': typeof ChromeAppIndexRoute
  '/internal/': typeof ChromeInternalIndexRoute
  '/internal/ai-sessions/$sessionDocumentId': typeof ChromeInternalAiSessionsSessionDocumentIdRoute
  '/internal/audits/$auditId': typeof ChromeInternalAuditsAuditIdRoute
  '/internal/cache/$cacheStateId': typeof ChromeInternalCacheCacheStateIdRoute
  '/internal/shops/$shopId': typeof ChromeInternalShopsShopIdRoute
  '/internal/users/$userId': typeof ChromeInternalUsersUserIdRoute
  '/internal/webhooks/$deliveryId': typeof ChromeInternalWebhooksDeliveryIdRoute
  '/internal/workflows/$jobId': typeof ChromeInternalWorkflowsJobIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/install': typeof ChromeInstallRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-sent': typeof AuthResetSentRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof ChromeIndexRoute
  '/app/copilot': typeof ChromeAppCopilotRoute
  '/app/explorer': typeof ChromeAppExplorerRoute
  '/app/settings': typeof ChromeAppSettingsRoute
  '/app/workflows': typeof ChromeAppWorkflowsRoute
  '/internal/ai-sessions': typeof ChromeInternalAiSessionsRouteWithChildren
  '/internal/audits': typeof ChromeInternalAuditsRouteWithChildren
  '/internal/cache': typeof ChromeInternalCacheRouteWithChildren
  '/internal/shops': typeof ChromeInternalShopsRouteWithChildren
  '/internal/users': typeof ChromeInternalUsersRouteWithChildren
  '/internal/webhooks': typeof ChromeInternalWebhooksRouteWithChildren
  '/internal/workflows': typeof ChromeInternalWorkflowsRouteWithChildren
  '/app': typeof ChromeAppIndexRoute
  '/internal': typeof ChromeInternalIndexRoute
  '/internal/ai-sessions/$sessionDocumentId': typeof ChromeInternalAiSessionsSessionDocumentIdRoute
  '/internal/audits/$auditId': typeof ChromeInternalAuditsAuditIdRoute
  '/internal/cache/$cacheStateId': typeof ChromeInternalCacheCacheStateIdRoute
  '/internal/shops/$shopId': typeof ChromeInternalShopsShopIdRoute
  '/internal/users/$userId': typeof ChromeInternalUsersUserIdRoute
  '/internal/webhooks/$deliveryId': typeof ChromeInternalWebhooksDeliveryIdRoute
  '/internal/workflows/$jobId': typeof ChromeInternalWorkflowsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chrome': typeof ChromeRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_chrome/app': typeof ChromeAppRouteWithChildren
  '/_chrome/install': typeof ChromeInstallRoute
  '/_chrome/internal': typeof ChromeInternalRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-sent': typeof AuthResetSentRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_chrome/': typeof ChromeIndexRoute
  '/_chrome/app/copilot': typeof ChromeAppCopilotRoute
  '/_chrome/app/explorer': typeof ChromeAppExplorerRoute
  '/_chrome/app/settings': typeof ChromeAppSettingsRoute
  '/_chrome/app/workflows': typeof ChromeAppWorkflowsRoute
  '/_chrome/internal/ai-sessions': typeof ChromeInternalAiSessionsRouteWithChildren
  '/_chrome/internal/audits': typeof ChromeInternalAuditsRouteWithChildren
  '/_chrome/internal/cache': typeof ChromeInternalCacheRouteWithChildren
  '/_chrome/internal/shops': typeof ChromeInternalShopsRouteWithChildren
  '/_chrome/internal/users': typeof ChromeInternalUsersRouteWithChildren
  '/_chrome/internal/webhooks': typeof ChromeInternalWebhooksRouteWithChildren
  '/_chrome/internal/workflows': typeof ChromeInternalWorkflowsRouteWithChildren
  '/_chrome/app/': typeof ChromeAppIndexRoute
  '/_chrome/internal/': typeof ChromeInternalIndexRoute
  '/_chrome/internal/ai-sessions/$sessionDocumentId': typeof ChromeInternalAiSessionsSessionDocumentIdRoute
  '/_chrome/internal/audits/$auditId': typeof ChromeInternalAuditsAuditIdRoute
  '/_chrome/internal/cache/$cacheStateId': typeof ChromeInternalCacheCacheStateIdRoute
  '/_chrome/internal/shops/$shopId': typeof ChromeInternalShopsShopIdRoute
  '/_chrome/internal/users/$userId': typeof ChromeInternalUsersUserIdRoute
  '/_chrome/internal/webhooks/$deliveryId': typeof ChromeInternalWebhooksDeliveryIdRoute
  '/_chrome/internal/workflows/$jobId': typeof ChromeInternalWorkflowsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/install'
    | '/internal'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/reset-sent'
    | '/auth/sign-in'
    | '/app/copilot'
    | '/app/explorer'
    | '/app/settings'
    | '/app/workflows'
    | '/internal/ai-sessions'
    | '/internal/audits'
    | '/internal/cache'
    | '/internal/shops'
    | '/internal/users'
    | '/internal/webhooks'
    | '/internal/workflows'
    | '/app/'
    | '/internal/'
    | '/internal/ai-sessions/$sessionDocumentId'
    | '/internal/audits/$auditId'
    | '/internal/cache/$cacheStateId'
    | '/internal/shops/$shopId'
    | '/internal/users/$userId'
    | '/internal/webhooks/$deliveryId'
    | '/internal/workflows/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/install'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/reset-sent'
    | '/auth/sign-in'
    | '/'
    | '/app/copilot'
    | '/app/explorer'
    | '/app/settings'
    | '/app/workflows'
    | '/internal/ai-sessions'
    | '/internal/audits'
    | '/internal/cache'
    | '/internal/shops'
    | '/internal/users'
    | '/internal/webhooks'
    | '/internal/workflows'
    | '/app'
    | '/internal'
    | '/internal/ai-sessions/$sessionDocumentId'
    | '/internal/audits/$auditId'
    | '/internal/cache/$cacheStateId'
    | '/internal/shops/$shopId'
    | '/internal/users/$userId'
    | '/internal/webhooks/$deliveryId'
    | '/internal/workflows/$jobId'
  id:
    | '__root__'
    | '/_chrome'
    | '/auth'
    | '/_chrome/app'
    | '/_chrome/install'
    | '/_chrome/internal'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/reset-sent'
    | '/auth/sign-in'
    | '/_chrome/'
    | '/_chrome/app/copilot'
    | '/_chrome/app/explorer'
    | '/_chrome/app/settings'
    | '/_chrome/app/workflows'
    | '/_chrome/internal/ai-sessions'
    | '/_chrome/internal/audits'
    | '/_chrome/internal/cache'
    | '/_chrome/internal/shops'
    | '/_chrome/internal/users'
    | '/_chrome/internal/webhooks'
    | '/_chrome/internal/workflows'
    | '/_chrome/app/'
    | '/_chrome/internal/'
    | '/_chrome/internal/ai-sessions/$sessionDocumentId'
    | '/_chrome/internal/audits/$auditId'
    | '/_chrome/internal/cache/$cacheStateId'
    | '/_chrome/internal/shops/$shopId'
    | '/_chrome/internal/users/$userId'
    | '/_chrome/internal/webhooks/$deliveryId'
    | '/_chrome/internal/workflows/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChromeRoute: typeof ChromeRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chrome': {
      id: '/_chrome'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chrome/': {
      id: '/_chrome/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChromeIndexRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-sent': {
      id: '/auth/reset-sent'
      path: '/reset-sent'
      fullPath: '/auth/reset-sent'
      preLoaderRoute: typeof AuthResetSentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_chrome/internal': {
      id: '/_chrome/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof ChromeInternalRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/_chrome/install': {
      id: '/_chrome/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof ChromeInstallRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/_chrome/app': {
      id: '/_chrome/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ChromeAppRouteImport
      parentRoute: typeof ChromeRoute
    }
    '/_chrome/internal/': {
      id: '/_chrome/internal/'
      path: '/'
      fullPath: '/internal/'
      preLoaderRoute: typeof ChromeInternalIndexRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/app/': {
      id: '/_chrome/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ChromeAppIndexRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/internal/workflows': {
      id: '/_chrome/internal/workflows'
      path: '/workflows'
      fullPath: '/internal/workflows'
      preLoaderRoute: typeof ChromeInternalWorkflowsRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/webhooks': {
      id: '/_chrome/internal/webhooks'
      path: '/webhooks'
      fullPath: '/internal/webhooks'
      preLoaderRoute: typeof ChromeInternalWebhooksRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/users': {
      id: '/_chrome/internal/users'
      path: '/users'
      fullPath: '/internal/users'
      preLoaderRoute: typeof ChromeInternalUsersRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/shops': {
      id: '/_chrome/internal/shops'
      path: '/shops'
      fullPath: '/internal/shops'
      preLoaderRoute: typeof ChromeInternalShopsRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/cache': {
      id: '/_chrome/internal/cache'
      path: '/cache'
      fullPath: '/internal/cache'
      preLoaderRoute: typeof ChromeInternalCacheRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/audits': {
      id: '/_chrome/internal/audits'
      path: '/audits'
      fullPath: '/internal/audits'
      preLoaderRoute: typeof ChromeInternalAuditsRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/internal/ai-sessions': {
      id: '/_chrome/internal/ai-sessions'
      path: '/ai-sessions'
      fullPath: '/internal/ai-sessions'
      preLoaderRoute: typeof ChromeInternalAiSessionsRouteImport
      parentRoute: typeof ChromeInternalRoute
    }
    '/_chrome/app/workflows': {
      id: '/_chrome/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof ChromeAppWorkflowsRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/app/settings': {
      id: '/_chrome/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof ChromeAppSettingsRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/app/explorer': {
      id: '/_chrome/app/explorer'
      path: '/explorer'
      fullPath: '/app/explorer'
      preLoaderRoute: typeof ChromeAppExplorerRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/app/copilot': {
      id: '/_chrome/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof ChromeAppCopilotRouteImport
      parentRoute: typeof ChromeAppRoute
    }
    '/_chrome/internal/workflows/$jobId': {
      id: '/_chrome/internal/workflows/$jobId'
      path: '/$jobId'
      fullPath: '/internal/workflows/$jobId'
      preLoaderRoute: typeof ChromeInternalWorkflowsJobIdRouteImport
      parentRoute: typeof ChromeInternalWorkflowsRoute
    }
    '/_chrome/internal/webhooks/$deliveryId': {
      id: '/_chrome/internal/webhooks/$deliveryId'
      path: '/$deliveryId'
      fullPath: '/internal/webhooks/$deliveryId'
      preLoaderRoute: typeof ChromeInternalWebhooksDeliveryIdRouteImport
      parentRoute: typeof ChromeInternalWebhooksRoute
    }
    '/_chrome/internal/users/$userId': {
      id: '/_chrome/internal/users/$userId'
      path: '/$userId'
      fullPath: '/internal/users/$userId'
      preLoaderRoute: typeof ChromeInternalUsersUserIdRouteImport
      parentRoute: typeof ChromeInternalUsersRoute
    }
    '/_chrome/internal/shops/$shopId': {
      id: '/_chrome/internal/shops/$shopId'
      path: '/$shopId'
      fullPath: '/internal/shops/$shopId'
      preLoaderRoute: typeof ChromeInternalShopsShopIdRouteImport
      parentRoute: typeof ChromeInternalShopsRoute
    }
    '/_chrome/internal/cache/$cacheStateId': {
      id: '/_chrome/internal/cache/$cacheStateId'
      path: '/$cacheStateId'
      fullPath: '/internal/cache/$cacheStateId'
      preLoaderRoute: typeof ChromeInternalCacheCacheStateIdRouteImport
      parentRoute: typeof ChromeInternalCacheRoute
    }
    '/_chrome/internal/audits/$auditId': {
      id: '/_chrome/internal/audits/$auditId'
      path: '/$auditId'
      fullPath: '/internal/audits/$auditId'
      preLoaderRoute: typeof ChromeInternalAuditsAuditIdRouteImport
      parentRoute: typeof ChromeInternalAuditsRoute
    }
    '/_chrome/internal/ai-sessions/$sessionDocumentId': {
      id: '/_chrome/internal/ai-sessions/$sessionDocumentId'
      path: '/$sessionDocumentId'
      fullPath: '/internal/ai-sessions/$sessionDocumentId'
      preLoaderRoute: typeof ChromeInternalAiSessionsSessionDocumentIdRouteImport
      parentRoute: typeof ChromeInternalAiSessionsRoute
    }
  }
}

interface ChromeAppRouteChildren {
  ChromeAppCopilotRoute: typeof ChromeAppCopilotRoute
  ChromeAppExplorerRoute: typeof ChromeAppExplorerRoute
  ChromeAppSettingsRoute: typeof ChromeAppSettingsRoute
  ChromeAppWorkflowsRoute: typeof ChromeAppWorkflowsRoute
  ChromeAppIndexRoute: typeof ChromeAppIndexRoute
}

const ChromeAppRouteChildren: ChromeAppRouteChildren = {
  ChromeAppCopilotRoute: ChromeAppCopilotRoute,
  ChromeAppExplorerRoute: ChromeAppExplorerRoute,
  ChromeAppSettingsRoute: ChromeAppSettingsRoute,
  ChromeAppWorkflowsRoute: ChromeAppWorkflowsRoute,
  ChromeAppIndexRoute: ChromeAppIndexRoute,
}

const ChromeAppRouteWithChildren = ChromeAppRoute._addFileChildren(
  ChromeAppRouteChildren,
)

interface ChromeInternalAiSessionsRouteChildren {
  ChromeInternalAiSessionsSessionDocumentIdRoute: typeof ChromeInternalAiSessionsSessionDocumentIdRoute
}

const ChromeInternalAiSessionsRouteChildren: ChromeInternalAiSessionsRouteChildren =
  {
    ChromeInternalAiSessionsSessionDocumentIdRoute:
      ChromeInternalAiSessionsSessionDocumentIdRoute,
  }

const ChromeInternalAiSessionsRouteWithChildren =
  ChromeInternalAiSessionsRoute._addFileChildren(
    ChromeInternalAiSessionsRouteChildren,
  )

interface ChromeInternalAuditsRouteChildren {
  ChromeInternalAuditsAuditIdRoute: typeof ChromeInternalAuditsAuditIdRoute
}

const ChromeInternalAuditsRouteChildren: ChromeInternalAuditsRouteChildren = {
  ChromeInternalAuditsAuditIdRoute: ChromeInternalAuditsAuditIdRoute,
}

const ChromeInternalAuditsRouteWithChildren =
  ChromeInternalAuditsRoute._addFileChildren(ChromeInternalAuditsRouteChildren)

interface ChromeInternalCacheRouteChildren {
  ChromeInternalCacheCacheStateIdRoute: typeof ChromeInternalCacheCacheStateIdRoute
}

const ChromeInternalCacheRouteChildren: ChromeInternalCacheRouteChildren = {
  ChromeInternalCacheCacheStateIdRoute: ChromeInternalCacheCacheStateIdRoute,
}

const ChromeInternalCacheRouteWithChildren =
  ChromeInternalCacheRoute._addFileChildren(ChromeInternalCacheRouteChildren)

interface ChromeInternalShopsRouteChildren {
  ChromeInternalShopsShopIdRoute: typeof ChromeInternalShopsShopIdRoute
}

const ChromeInternalShopsRouteChildren: ChromeInternalShopsRouteChildren = {
  ChromeInternalShopsShopIdRoute: ChromeInternalShopsShopIdRoute,
}

const ChromeInternalShopsRouteWithChildren =
  ChromeInternalShopsRoute._addFileChildren(ChromeInternalShopsRouteChildren)

interface ChromeInternalUsersRouteChildren {
  ChromeInternalUsersUserIdRoute: typeof ChromeInternalUsersUserIdRoute
}

const ChromeInternalUsersRouteChildren: ChromeInternalUsersRouteChildren = {
  ChromeInternalUsersUserIdRoute: ChromeInternalUsersUserIdRoute,
}

const ChromeInternalUsersRouteWithChildren =
  ChromeInternalUsersRoute._addFileChildren(ChromeInternalUsersRouteChildren)

interface ChromeInternalWebhooksRouteChildren {
  ChromeInternalWebhooksDeliveryIdRoute: typeof ChromeInternalWebhooksDeliveryIdRoute
}

const ChromeInternalWebhooksRouteChildren: ChromeInternalWebhooksRouteChildren =
  {
    ChromeInternalWebhooksDeliveryIdRoute:
      ChromeInternalWebhooksDeliveryIdRoute,
  }

const ChromeInternalWebhooksRouteWithChildren =
  ChromeInternalWebhooksRoute._addFileChildren(
    ChromeInternalWebhooksRouteChildren,
  )

interface ChromeInternalWorkflowsRouteChildren {
  ChromeInternalWorkflowsJobIdRoute: typeof ChromeInternalWorkflowsJobIdRoute
}

const ChromeInternalWorkflowsRouteChildren: ChromeInternalWorkflowsRouteChildren =
  {
    ChromeInternalWorkflowsJobIdRoute: ChromeInternalWorkflowsJobIdRoute,
  }

const ChromeInternalWorkflowsRouteWithChildren =
  ChromeInternalWorkflowsRoute._addFileChildren(
    ChromeInternalWorkflowsRouteChildren,
  )

interface ChromeInternalRouteChildren {
  ChromeInternalAiSessionsRoute: typeof ChromeInternalAiSessionsRouteWithChildren
  ChromeInternalAuditsRoute: typeof ChromeInternalAuditsRouteWithChildren
  ChromeInternalCacheRoute: typeof ChromeInternalCacheRouteWithChildren
  ChromeInternalShopsRoute: typeof ChromeInternalShopsRouteWithChildren
  ChromeInternalUsersRoute: typeof ChromeInternalUsersRouteWithChildren
  ChromeInternalWebhooksRoute: typeof ChromeInternalWebhooksRouteWithChildren
  ChromeInternalWorkflowsRoute: typeof ChromeInternalWorkflowsRouteWithChildren
  ChromeInternalIndexRoute: typeof ChromeInternalIndexRoute
}

const ChromeInternalRouteChildren: ChromeInternalRouteChildren = {
  ChromeInternalAiSessionsRoute: ChromeInternalAiSessionsRouteWithChildren,
  ChromeInternalAuditsRoute: ChromeInternalAuditsRouteWithChildren,
  ChromeInternalCacheRoute: ChromeInternalCacheRouteWithChildren,
  ChromeInternalShopsRoute: ChromeInternalShopsRouteWithChildren,
  ChromeInternalUsersRoute: ChromeInternalUsersRouteWithChildren,
  ChromeInternalWebhooksRoute: ChromeInternalWebhooksRouteWithChildren,
  ChromeInternalWorkflowsRoute: ChromeInternalWorkflowsRouteWithChildren,
  ChromeInternalIndexRoute: ChromeInternalIndexRoute,
}

const ChromeInternalRouteWithChildren = ChromeInternalRoute._addFileChildren(
  ChromeInternalRouteChildren,
)

interface ChromeRouteChildren {
  ChromeAppRoute: typeof ChromeAppRouteWithChildren
  ChromeInstallRoute: typeof ChromeInstallRoute
  ChromeInternalRoute: typeof ChromeInternalRouteWithChildren
  ChromeIndexRoute: typeof ChromeIndexRoute
}

const ChromeRouteChildren: ChromeRouteChildren = {
  ChromeAppRoute: ChromeAppRouteWithChildren,
  ChromeInstallRoute: ChromeInstallRoute,
  ChromeInternalRoute: ChromeInternalRouteWithChildren,
  ChromeIndexRoute: ChromeIndexRoute,
}

const ChromeRouteWithChildren =
  ChromeRoute._addFileChildren(ChromeRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthResetSentRoute: typeof AuthResetSentRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResetSentRoute: AuthResetSentRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChromeRoute: ChromeRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
