/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as InstallRouteImport } from './routes/install'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OpsWebhooksRouteImport } from './routes/ops.webhooks'
import { Route as OpsTenantsRouteImport } from './routes/ops.tenants'
import { Route as OpsSyncJobsRouteImport } from './routes/ops.sync-jobs'
import { Route as OpsAiTracesRouteImport } from './routes/ops.ai-traces'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppExplorerRouteImport } from './routes/app.explorer'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'

const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OpsWebhooksRoute = OpsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => OpsRoute,
} as any)
const OpsTenantsRoute = OpsTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSyncJobsRoute = OpsSyncJobsRouteImport.update({
  id: '/sync-jobs',
  path: '/sync-jobs',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAiTracesRoute = OpsAiTracesRouteImport.update({
  id: '/ai-traces',
  path: '/ai-traces',
  getParentRoute: () => OpsRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/install': typeof InstallRoute
  '/ops': typeof OpsRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/explorer': typeof AppExplorerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/ops/ai-traces': typeof OpsAiTracesRoute
  '/ops/sync-jobs': typeof OpsSyncJobsRoute
  '/ops/tenants': typeof OpsTenantsRoute
  '/ops/webhooks': typeof OpsWebhooksRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/explorer': typeof AppExplorerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/ops/ai-traces': typeof OpsAiTracesRoute
  '/ops/sync-jobs': typeof OpsSyncJobsRoute
  '/ops/tenants': typeof OpsTenantsRoute
  '/ops/webhooks': typeof OpsWebhooksRoute
  '/app': typeof AppIndexRoute
  '/ops': typeof OpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/install': typeof InstallRoute
  '/ops': typeof OpsRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/explorer': typeof AppExplorerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/ops/ai-traces': typeof OpsAiTracesRoute
  '/ops/sync-jobs': typeof OpsSyncJobsRoute
  '/ops/tenants': typeof OpsTenantsRoute
  '/ops/webhooks': typeof OpsWebhooksRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/install'
    | '/ops'
    | '/app/copilot'
    | '/app/explorer'
    | '/app/settings'
    | '/app/workflows'
    | '/ops/ai-traces'
    | '/ops/sync-jobs'
    | '/ops/tenants'
    | '/ops/webhooks'
    | '/app/'
    | '/ops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/app/copilot'
    | '/app/explorer'
    | '/app/settings'
    | '/app/workflows'
    | '/ops/ai-traces'
    | '/ops/sync-jobs'
    | '/ops/tenants'
    | '/ops/webhooks'
    | '/app'
    | '/ops'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/install'
    | '/ops'
    | '/app/copilot'
    | '/app/explorer'
    | '/app/settings'
    | '/app/workflows'
    | '/ops/ai-traces'
    | '/ops/sync-jobs'
    | '/ops/tenants'
    | '/ops/webhooks'
    | '/app/'
    | '/ops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InstallRoute: typeof InstallRoute
  OpsRoute: typeof OpsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/ops/webhooks': {
      id: '/ops/webhooks'
      path: '/webhooks'
      fullPath: '/ops/webhooks'
      preLoaderRoute: typeof OpsWebhooksRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/tenants': {
      id: '/ops/tenants'
      path: '/tenants'
      fullPath: '/ops/tenants'
      preLoaderRoute: typeof OpsTenantsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/sync-jobs': {
      id: '/ops/sync-jobs'
      path: '/sync-jobs'
      fullPath: '/ops/sync-jobs'
      preLoaderRoute: typeof OpsSyncJobsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/ai-traces': {
      id: '/ops/ai-traces'
      path: '/ai-traces'
      fullPath: '/ops/ai-traces'
      preLoaderRoute: typeof OpsAiTracesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explorer': {
      id: '/app/explorer'
      path: '/explorer'
      fullPath: '/app/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCopilotRoute: typeof AppCopilotRoute
  AppExplorerRoute: typeof AppExplorerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCopilotRoute: AppCopilotRoute,
  AppExplorerRoute: AppExplorerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OpsRouteChildren {
  OpsAiTracesRoute: typeof OpsAiTracesRoute
  OpsSyncJobsRoute: typeof OpsSyncJobsRoute
  OpsTenantsRoute: typeof OpsTenantsRoute
  OpsWebhooksRoute: typeof OpsWebhooksRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAiTracesRoute: OpsAiTracesRoute,
  OpsSyncJobsRoute: OpsSyncJobsRoute,
  OpsTenantsRoute: OpsTenantsRoute,
  OpsWebhooksRoute: OpsWebhooksRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InstallRoute: InstallRoute,
  OpsRoute: OpsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
